version: '3.8'

services:
  db:
    image: postgres:13
    container_name: finance_manager_db
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - finance_network

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt

volumes:
  db_data:

networks:
  finance_network:
