name: Run govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.22
          go-package: ./...